builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.project={{.ProjectName}} -X main.version={{ .Version }} -X main.commit={{.Commit}} -X main.short={{.ShortCommit}} -X main.date={{ .CommitDate }}
    goos:
      - linux
      - windows
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^readme:"
