# https://taskfile.dev

version: '3'

vars:
  APP: autotag
dotenv:
  - .env
tasks:
  release:
    cmds:
      - goreleaser release --clean

  build_snapshot:
    cmds:
      - goreleaser build --clean --snapshot

  build:
    cmds:
      - go build -o ./dist/{{.APP}}{{exeExt}} .

