# https://taskfile.dev

version: '3'

vars:
  APP: autotag

tasks:
  build:
    cmds:
      - go build -o ./dist/{{.APP}}{{exeExt}} .

  run:
    cmds:
      - ./dist/{{.APP}}{{exeExt}}

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
